version: "3"
services:
  web:
    build: .
    command: nodemon --inspect=0.0.0.0:5858 ./server.js
    image: yeapiekiyay/spin-with-friends-app
    volumes:
      - "./src:/app"
      - "./package.json:/package.json"
    ports:
      - "8000:80"
      - "5858:5858"